{% set name = "pennylane-honeywell" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-honeywell/archive/v{{ version }}.tar.gz
  sha256: 1641fae0f1e3e14010a88ba461928bdd1868dba170d1bd97ea72a6a23397d284

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pennylane >=0.23
    - pyjwt
    - python >=3.6
    - requests
    - toml

test:
  imports:
    - pennylane_honeywell
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://xanadu.ai
  summary: |
    The PennyLane-Honeywell plugin integrates Honeywell Quantum Solutions' ion-trap
    quantum computing hardware with with PennyLane's quantum machine learning capabilities.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/PennyLaneAI/pennylane-honeywell
  doc_url: https://pennylane-honeywell.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
